import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type Entity = Record<string, any>;
const api = async (path: string, init?: RequestInit) => { const response = await fetch(path, { ...init, headers: { 'content-type': 'application/json', ...(init?.headers ?? {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.message ?? body.error ?? `${response.status}`); return body; };
const post = (path: string, body: unknown = {}) => api(path, { method: 'POST', body: JSON.stringify(body), headers: { 'idempotency-key': crypto.randomUUID() } });
const stateSteps = ['INTAKE','PLANNING_GRADE','AWAITING_PLANNING_APPROVAL','TECHNICAL_DISCOVERY','IMPLEMENTATION_GRADE','AWAITING_IMPLEMENTATION_APPROVAL','DONE'];

function App() {
  const [status,setStatus]=useState<Entity>(); const [resources,setResources]=useState<Entity>(); const [scheduler,setScheduler]=useState<Entity>();
  const [projects,setProjects]=useState<Entity[]>([]); const [repos,setRepos]=useState<Entity[]>([]); const [items,setItems]=useState<Entity[]>([]); const [questions,setQuestions]=useState<Entity[]>([]); const [runs,setRuns]=useState<Entity[]>([]);
  const [selected,setSelected]=useState<string>(); const [detail,setDetail]=useState<Entity>(); const [error,setError]=useState(''); const [busy,setBusy]=useState('');
  const refresh=async()=>{ try { const [s,rs,q,p,r,w,qu,ru]=await Promise.all([api('/system/status'),api('/resources'),api('/scheduler'),api('/projects'),api('/repositories'),api('/work-items'),api('/questions'),api('/runs')]); setStatus(s);setResources(rs);setScheduler(q);setProjects(p);setRepos(r);setItems(w);setQuestions(qu);setRuns(ru); if(selected)setDetail(await api(`/work-items/${selected}/detail`)); setError(''); } catch(e){setError(String(e));} };
  useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),5000);return()=>clearInterval(timer)},[selected]);
  const action=async(label:string,fn:()=>Promise<any>)=>{setBusy(label);setError('');try{await fn();await refresh()}catch(e){setError(String(e))}finally{setBusy('')}};
  const submit=(handler:(data:any)=>Promise<any>)=>(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget;const data=Object.fromEntries(new FormData(form));void action('Saving',()=>handler(data).then(()=>{form.reset()}));};
  const selectedItem=detail?.item; const planningArtifact=(detail?.artifacts??[]).find((value:Entity)=>value.type==='planning'); const implementationArtifact=(detail?.artifacts??[]).find((value:Entity)=>value.type==='implementation');
  const nextAction=()=>{ if(!selectedItem)return null; const id=selectedItem.id,s=selectedItem.state;
    if(s==='INTAKE')return <button onClick={()=>action('Discovering',()=>post(`/work-items/${id}/discovery`,{}))}>Complete discovery</button>;
    if(s==='PLANNING_GRADE')return <button onClick={()=>action('Planning',()=>post(`/work-items/${id}/planning`))}>Start real planning</button>;
    if(s==='AWAITING_PLANNING_APPROVAL')return <div className="reviewActions"><button onClick={()=>action('Approving plan',()=>post(`/work-items/${id}/planning-approval`,{artifactHash:planningArtifact?.contentHash,approver:'Michael'}))} disabled={!planningArtifact}>Approve planning revision</button><form onSubmit={submit(data=>post(`/work-items/${id}/planning-feedback`,{artifactHash:planningArtifact?.contentHash,feedback:data.feedback,actor:'Michael'}))}><textarea name="feedback" placeholder="Explain what should change in the plan" required/><button className="secondary" disabled={!planningArtifact}>Request planning revision</button></form></div>;
    if(s==='TECHNICAL_DISCOVERY')return <button onClick={()=>action('Technical discovery',()=>post(`/work-items/${id}/technical-discovery`,{}))}>Complete technical discovery</button>;
    if(s==='IMPLEMENTATION_GRADE')return <button onClick={()=>action('Implementing',()=>post(`/work-items/${id}/implementation`))}>Start real Build Auto</button>;
    if(s==='AWAITING_IMPLEMENTATION_APPROVAL')return <button onClick={()=>action('Approving implementation',()=>post(`/work-items/${id}/implementation-approval`,{artifactHash:implementationArtifact?.contentHash,approver:'Michael'}))}>Approve implementation</button>;
    return <span className="done">{s==='DONE'?'Complete':'Waiting for an answer'}</span> };
  return <><header><div><b>MIC</b><span>Local control plane</span></div><a href="/docs" target="_blank">API docs ↗</a></header><main>
    <section className="hero"><div><small>SYSTEM</small><h1>{status?.status==='ok'?'Ready to work':'Connecting…'}</h1><p>{status?.database??'database'} · router {status?.router?.status??'unknown'}</p></div><div className="metrics"><Metric n={status?.counts?.projects??0} label="Projects"/><Metric n={status?.counts?.workItems??0} label="Work items"/><Metric n={scheduler?.pendingOutbox??0} label="Queued"/><Metric n={`${Math.round(resources?.availableMiB??0).toLocaleString()} MB`} label="Memory free"/></div></section>
    {error&&<div className="error">{error}</div>}{busy&&<div className="busy">{busy}…</div>}
    <div className="grid"><section className="panel"><h2>Projects</h2><form onSubmit={submit(data=>post('/projects',{name:data.name}))}><input name="name" placeholder="New project name" required/><button>Add</button></form>{projects.map(p=><article key={p.id}><strong>{p.name}</strong><code>{p.id}</code><form onSubmit={submit(data=>post(`/projects/${p.id}/repositories`,{path:data.path,baseBranch:data.baseBranch||'main'}))}><input name="path" placeholder="/absolute/path/to/git/repo" required/><input name="baseBranch" placeholder="main"/><button>Attach repo</button></form>{repos.filter(r=>r.projectId===p.id).map(r=><p className="repo" key={r.id}>{r.path} · {r.baseBranch}</p>)}</article>)}</section>
    <section className="panel"><h2>Work items</h2><form onSubmit={submit(data=>post('/work-items',{projectId:data.projectId,title:data.title,intent:data.intent}))}><select name="projectId" required><option value="">Choose project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input name="title" placeholder="Title" required/><textarea name="intent" placeholder="What should MIC build?" required/><button>Create work item</button></form><div className="list">{items.map(w=><button className={selected===w.id?'selected':''} key={w.id} onClick={()=>setSelected(w.id)}><span>{w.title}</span><em>{w.state}</em></button>)}</div></section></div>
    {selectedItem&&<section className="panel detail"><div className="detailHead"><div><small>WORK ITEM</small><h2>{selectedItem.title}</h2><p>{selectedItem.intent}</p></div>{nextAction()}</div><div className="timeline">{stateSteps.map(step=><span className={step===selectedItem.state?'current':stateSteps.indexOf(step)<stateSteps.indexOf(selectedItem.state)?'past':''} key={step}>{step.replaceAll('_',' ')}</span>)}</div><div className="columns"><Sub title="Runs">{(detail.runs??[]).map((r:Entity)=><article key={r.id}><b>{r.kind} · {r.status}</b><code>{r.id}</code><p>{r.result?.summary}</p>{r.status==='RUNNING'&&<button onClick={()=>action('Cancelling',()=>post(`/runs/${r.id}/cancel`))}>Cancel</button>}<details><summary>Logs and adapter state</summary><pre>{JSON.stringify(r.result?.rawAdapterState??{},null,2)}</pre></details></article>)}</Sub><Sub title="Artifacts & evidence">{(detail.artifacts??[]).map((a:Entity)=><article key={a.id}><b>{a.type}</b><p><a href={`/artifacts/${a.type}/${a.id}/content`} target="_blank">{a.path} ↗</a></p><code>{a.contentHash}</code></article>)}{(detail.runs??[]).flatMap((r:Entity)=>(r.result?.evidenceRefs??[]).map((e:string)=><p key={e}>{e}</p>))}</Sub><Sub title="Review history">{(detail.timeline??[]).filter((event:Entity)=>event.action==='planning.feedback').map((event:Entity)=><article key={event.id}><b>Planning revision requested</b><p>{event.detail?.feedback}</p><small>{event.actor}</small><code>{event.detail?.artifactHash}</code></article>)}{(detail.approvals??[]).map((a:Entity)=><article key={a.id}><b>{a.phase} approved</b><p>{a.approver}</p><code>{a.repositoryRevision}</code></article>)}</Sub></div></section>}
    <section className="panel"><h2>Open questions</h2>{questions.filter(q=>q.status==='OPEN').length===0?<p className="muted">No questions need an answer.</p>:questions.filter(q=>q.status==='OPEN').map(q=><article key={q.id}><b>{q.question}</b><form onSubmit={submit(data=>post(`/questions/${q.id}/answer`,{answer:data.answer,actor:'Michael'}))}><input name="answer" placeholder="Your answer" required/><button>Answer</button></form></article>)}</section>
  </main></>;
}
function Metric({n,label}:{n:any,label:string}){return <div><strong>{n}</strong><span>{label}</span></div>} function Sub({title,children}:{title:string,children:React.ReactNode}){return <div><h3>{title}</h3>{children}</div>}
createRoot(document.getElementById('root')!).render(<App/>);
